### ISSUE TITLE
似乎没有考虑文件夹名称存在小数点的情况

### ISSUE THREAD

**Issue by Newbe36524** [TevinLi/amWiki#125]
[Enter steps to reproduce:]

似乎没有考虑文件夹名称存在小数点的情况

**Atom**: 1.24.0-beta1 x64
**Electron**: 1.6.15
**OS**: Windows 10 1709
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package 1.2.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'D:\Repos\IDM\src\IDM.Wikiconfig.json'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'D:\Repos\IDM\src\IDM.Wikiconfig.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.updateWikiConfig (/packages/amWiki/build/manageWiki.js:133:44)
    at Object.addWiki (/packages/amWiki/build/manageWiki.js:61:22)
    at Object.checkAddWiki (/packages/amWiki/build/manageWiki.js:108:22)
    at /packages/amWiki/lib/main.js:142:37)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.24.0-beta1/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.24.0-beta1/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.24.0-beta1/resources/app/src/atom-environment.js:1253:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.24.0-beta1/resources/app/src/application-delegate.js:333:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -1:20.6.0 amWiki:makeNav (div.package-detail.panels-item)
     -0:53 amWiki:create (input.hidden-input)
     -0:40.5.0 tabs:close-other-tabs (div.title)
     -0:33 amWiki:makeNav (input.hidden-input)
```

### Non-Core Packages

```
amWiki 1.2.1 
minimap 4.29.8 
tidy-markdown 3.0.1 
```

**Comment by mikusjelly** [comment]
'D:\Repos\IDM\src\IDM.Wikiconfig.json'， Wiki里面有这个东西么？

**Comment by Newbe36524** [comment]
@mikusjelly  config.json 这个文件就是 amWiki 的配置文件。
D:\Repos\IDM\src\IDM.Wiki 是我存放 amWiki 代码的文件夹

**Comment by Newbe36524** [comment]
@mikusjelly 似乎在 1.2.1 版本之前 的一些版本中，是没有这个问题的。后来才出现了这个问题

**Comment by mikusjelly** [comment]
@Newbe36524 

如果可以的话，麻烦写清楚Bug的重现步骤（[Enter steps to reproduce:]）。

我这里并没错出任何错误，估计没能准确理解你说的意思。

**Comment by Newbe36524** [comment]
@mikusjelly 

当点击菜单上的  手动更新 当前文库导航文件 时会弹出此错误。对此进行了一下研究：

---

分别经过以下尝试，均可以修复此错误：

- 将文件夹IDM.Wiki重命名为IDM.Wiki2
- 将文件夹复制到其他的硬盘，文件夹深度一致
- 将文件夹IDM.Wiki的内容全部复制到其他文件夹

但是，采用这冲方式，将原文件夹删除，然后复制将内容复制回原来的文件夹之后，依旧出错。

---

总结，原来的文件夹，不管怎么操作，都不能用，修改文件夹的名称或者移动到其他的文件夹就可以了。

**Comment by Newbe36524** [comment]
尝试重新安装amwiki 不能解决此问题

**Comment by mikusjelly** [comment]
@Newbe36524 没有任何问题。


![2018-03-19_105853](https://user-images.githubusercontent.com/2801072/37575922-9b3891b2-2b64-11e8-8087-ef012cf26bc0.png)

![2018-03-19_105901](https://user-images.githubusercontent.com/2801072/37575926-9f38f5d6-2b64-11e8-8f8e-3bf14d368fca.png)

**Comment by Newbe36524** [comment]
是的，只有特定的文件夹才会出现故障，不知道是否与 Test.Wiki 缓存在某处的数据有关。

**Comment by mikusjelly** [comment]
@Newbe36524 
你的错误提示为： no such file or directory, open 'D:\Repos\IDM\src\IDM.Wikiconfig.json'

而配置的实际路径：`D:\Repos\IDM\src\IDM.Wiki\config.json`，不知道你怎么弄的。
