### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pageMounts' of null

### ISSUE THREAD

**Issue by wangcailin** [TevinLi/amWiki#133]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package 1.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'pageMounts' of null

```
At /Users/wangcailin/.atom/packages/amWiki/build/makeMounts.js:45

TypeError: Cannot read property 'pageMounts' of null
    at Object._checkMountsAllow (/packages/amWiki/build/makeMounts.js:45:30)
    at Object.make (/packages/amWiki/build/makeMounts.js:21:23)
    at /packages/amWiki/lib/main.js:157:37)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -0:52.1.0 core:backspace (input.hidden-input)
     -0:51.7.0 core:confirm (input.hidden-input)
     -0:45.2.0 tree-view:move (span.name.icon.icon-file-directory)
     -0:42.9.0 core:backspace (input.hidden-input)
     -0:42.6.0 core:confirm (input.hidden-input)
     -0:35.9.0 tree-view:move (span.name.icon.icon-file-directory)
     -0:33.9.0 core:backspace (input.hidden-input)
     -0:33.5.0 core:confirm (input.hidden-input)
     -0:28.2.0 tree-view:move (span.name.icon.icon-file-directory)
     -0:26.5.0 core:backspace (input.hidden-input)
     -0:25.8.0 core:confirm (input.hidden-input)
     -0:19.1.0 tree-view:move (span.name.icon.icon-file-text)
 12x -0:17.1.0 core:backspace (input.hidden-input)
     -0:12.4.0 core:confirm (input.hidden-input)
     -0:07.1.0 core:save (input.hidden-input)
     -0:03.4.0 amWiki:makeMut (input.hidden-input)
```

### Non-Core Packages

```
amWiki 1.2.1 
language-mediawiki 2.2.0 
```

**Comment by xuelang-wang** [comment]
{
  "page-mounts": true
}
