### ISSUE TITLE
黏贴图片失败，报错信息：Uncaught TypeError: img.toPng is not a function

### ISSUE THREAD

**Issue by jacksoncode** [TevinLi/amWiki#138]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0-beta3 x64
**Electron**: 2.0.1
**OS**: Unknown Windows version
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package 1.2.1

### Stack Trace

Uncaught TypeError: img.toPng is not a function

```
At C:\Users\z00197330.CHINA\.atom\packages\amWiki\lib\richPaste.js:109

TypeError: img.toPng is not a function
    at Object._pasteImg (/packages/amWiki/lib/richPaste.js:109:33)
    at Object.paste (/packages/amWiki/lib/richPaste.js:66:22)
    at /packages/amWiki/lib/main.js:168:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.0-beta3/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.28.0-beta3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.28.0-beta3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.28.0-beta3/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:34.8.0 editor:newline (input.hidden-input)
     -1:34.7.0 markdown-writer:indent-list-line (input.hidden-input)
     -1:23.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:23.9.0 editor:newline (input.hidden-input)
     -1:23.6.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:23.6.0 editor:newline (input.hidden-input)
     -1:21.7.0 core:move-up (input.hidden-input)
     -1:20.5.0 markdown-writer:indent-list-line (input.hidden-input)
     -1:19.9.0 core:paste (input.hidden-input)
     -1:18.2.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:18 markdown-writer:indent-list-line (input.hidden-input)
     -1:17.4.0 core:move-up (input.hidden-input)
     -1:16.7.0 core:delete (input.hidden-input)
     -1:14.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:14.1.0 editor:newline (input.hidden-input)
     -0:36.9.0 amWiki:paste (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
amWiki 1.2.1 
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.24 
atom-github-theme 0.2.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-ternjs 0.18.3 
autoclose 0.0.2 
autocomplete-python 1.10.5 
awiki 0.3.1 
close-tags 0.6.0 
code-macro 0.1.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
github-2014 3.17.0 
github-2016-syntax 1.2.0 
github-2016-syntax-theme 0.0.0 
github-atom-light-syntax 0.5.0 
github-web 1.1.0 
gl-dark-syntax 3.0.0 
gl-light-syntax 3.0.0 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
jekyll 2.1.0 
language-liquid 0.6.0 
language-markdown 0.25.1 
language-mediawiki 2.2.0 
mac-github-syntax 1.3.9 
mac-os-ui 0.3.0 
markdown-pdf 2.1.0 
markdown-preview-plus 2.5.8 
markdown-writer 2.7.3 
material-ui 1.0.10 
metro-ui 2.2.2 
simplified-chinese-menu 5.3.5 
theme-realgithub 1.0.8 
wakatime undefined 
```

**Comment by cm3** [comment]
`toPng` is now `toPNG`. See the related issue https://github.com/bigyuki/markdown-image-helper/issues/14#issuecomment-399403711

**Comment by foryl** [comment]
找到对应的109行，toPng改为toPNG

**Comment by yifengyou** [comment]
> 找到对应的109行，toPng改为toPNG

nice~！
