### ISSUE TITLE
粘贴图片失败

### ISSUE THREAD

**Issue by zhilianyun889** [TevinLi/amWiki#160]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 ia32
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package 1.2.1

### Stack Trace

Uncaught TypeError: img.toPng is not a function

```
At C:\Users\MINN\.atom\packages\amWiki\lib\richPaste.js:109

TypeError: img.toPng is not a function
    at Object._pasteImg (/packages/amWiki/lib/richPaste.js:109:33)
    at Object.paste (/packages/amWiki/lib/richPaste.js:66:22)
    at /packages/amWiki/lib/main.js:168:35)
    at CommandRegistry.handleCommandEvent (F:/文库/Atom/resources/app/static/<embedded>:11:349963)
    at KeymapManager.dispatchCommandEvent (F:/文库/Atom/resources/app/static/<embedded>:11:1231297)
    at KeymapManager.handleKeyboardEvent (F:/文库/Atom/resources/app/static/<embedded>:11:1227431)
    at WindowEventHandler.handleDocumentKeyEvent (F:/文库/Atom/resources/app/static/<embedded>:11:284820)
```

### Commands

```
  8x -4:26.9.0 core:backspace (atom-text-editor.editor.mini)
     -4:18.3.0 core:cancel (atom-text-editor.editor.mini)
     -4:05.2.0 core:backspace (atom-text-editor.editor.has-selection)
     -4:04.4.0 core:undo (atom-text-editor.editor)
     -3:56.9.0 amWiki:browser (atom-text-editor.editor)
     -3:31.9.0 core:select-all (input.hidden-input)
     -3:31.2.0 core:paste (input.hidden-input)
  2x -3:30.5.0 core:save (input.hidden-input)
     -2:54.7.0 tree-view:move (div.tool-panel.tree-view)
 12x -2:52.9.0 core:backspace (input.hidden-input)
     -2:38.1.0 core:confirm (input.hidden-input)
     -2:24.1.0 tree-view:duplicate (span.name.icon.icon-file-directory)
     -2:22.5.0 core:cancel (input.hidden-input)
     -0:41.2.0 editor:consolidate-selections (input.hidden-input)
     -0:41.2.0 core:cancel (input.hidden-input)
     -0:36.2.0 amWiki:paste (input.hidden-input)
```

### Non-Core Packages

```
amWiki 1.2.1 
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
docblockr 0.13.7 
simplified-chinese-menu 5.3.5 
```

**Comment by linharrrrrt** [comment]
编辑你的/Users/superdanny/.atom/packages/amWiki/lib/richPaste.js第109行
img.toPng
改成
img.toPNG
