### ISSUE TITLE
Uncaught SyntaxError: Unexpected token /

### ISSUE THREAD

**Issue by ymzuiku** [TevinLi/amWiki#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.3
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package, v0.2.6

### Stack Trace

Uncaught SyntaxError: Unexpected token /

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FUsers%2Fym%2FDesktop%2Fakwiki%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fym%2FDesktop%2Fakwiki%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2F48%2Fxpj64q2161qdclh_lt3yfyf40000gn%2FT%2F%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x1F5%3A0x19%3A0x34%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22HOME%22%3A%22%2FUsers%2Fym%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.Pgpr1yaYOY%2FRender%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.BXq2nYD9ZA%2FListeners%22%2C%22PATH%22%3A%22%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22LOGNAME%22%3A%22ym%22%2C%22XPC_SERVICE_NAME%22%3A%22com.github.atom.175712%22%2C%22USER%22%3A%22ym%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2Fym%2F.atom%22%7D%2C%22appVersion%22%3A%221.7.4%22%2C%22atomHome%22%3A%22%2FUsers%2Fym%2F.atom%22%2C%22shellLoadTime%22%3A225%7D:2

SyntaxError: Unexpected token /
    at Object.parse (native)
    at Object.module.exports.buildAt (/Users/ym/.atom/packages/amWiki/lib/creator.js:77:23)
    at Object.module.exports.createWiki (/Users/ym/.atom/packages/amwiki/lib/main.coffee:68:13)
    at atom-workspace.subscriptions.add.atom.commands.add.amWiki:create (/Users/ym/.atom/packages/amwiki/lib/main.coffee:24:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -2:36.4.0 core:paste (atom-text-editor.editor.is-focused)
     -2:34.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:33.2.0 amWiki:pasteImg (atom-text-editor.editor.is-focused)
     -2:21.1.0 editor:copy-path (atom-text-editor.editor.is-focused)
     -2:20.1.0 amWiki:pasteImg (atom-text-editor.editor.is-focused)
     -2:18.2.0 core:paste (atom-text-editor.editor.is-focused)
     -2:17.2.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -2:13 amWiki:pasteImg (atom-text-editor.editor.is-focused)
     -1:30.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 12x -1:23 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:20.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:20.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -0:50.9.0 amWiki:create (div.package-detail.panels-item)
     -0:05.8.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:00.4.0 amWiki:create (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
amWiki, v0.2.6
atom-html-preview, v0.1.19
atom-ternjs, v0.14.1
atomatigit, v1.5.5
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.12
language-babel, v2.23.0
language-diff, v0.4.0
linter, v1.11.4
linter-coffeescript, v1.0.0
linter-eslint, v7.2.2
material-syntax, v0.5.0
pigments, v0.26.3

# Dev
No dev packages
```

**Comment by TevinLi** [comment]
这问题应该是config.json解析失败了，需要使用json格式，现在已经增加了弹窗提示，不再报错
