### ISSUE TITLE
0.8版本出现Uncaught URIError

### ISSUE THREAD

**Issue by jimmywzm** [TevinLi/amWiki#31]
**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package, v0.8.0

### Stack Trace

Uncaught URIError: URI malformed

```
At /Users/jimmywang/.atom/packages/amWiki/files/gbk.js:77

URIError: URI malformed
    at decodeURIComponent (native)
    at /Users/jimmywang/.atom/packages/amWiki/files/gbk.js:77:24
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.decode (/Users/jimmywang/.atom/packages/amWiki/files/gbk.js:76:16)
    at Server.<anonymous> (/Users/jimmywang/.atom/packages/amWiki/lib/webServer.js:102:32)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
```

### Commands

```
     -2:09.6.0 core:save (input.hidden-input)
     -2:05.6.0 amWiki:runServer (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
amWiki, v0.8.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

**Comment by YaoXuanZhi** [comment]
以下内容摘自[其他网站](http://www.tuicool.com/articles/aYrm63)

## 问题：`Uncaught URIError: URI malformed`

### 相关错误：`URIError: malformed URI sequence`

**原因**：无效的 decodeURIComponent 调用所致。

**解决方案**：按照错误指出的行号，检查 decodeURIComponent 调用，它是正确的。

**其他相关**：`XMLHttpRequest cannot load http://some/url/ . No ‘Access-Control-Allow-Origin’ header is present on the requested resource`

### 相关错误：`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at`
http://some/url/

**原因**：错误肯定是使用 XMLHttpRequest 引起的。

**解决方案**：确保请求的 URL 是正确的，它遵循 同源策略 。最好的方法是从代码中找到错误信息指出的 URL 。

**其他相关**：`InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`

### 相关错误：InvalidStateError, DOMException code 11

**原因**：代码调用的方法在当前状态无法调用。通常由 XMLHttpRequest 引起，在方法准备完毕之前调用它会引起错误。

>var xhr = new XMLHttpRequest();
xhr.setRequestHeader('Some-Header', 'val');
这时就会出错，因为 setRequestHeader 方法只能在 xhr.open 方法之后调用。

**解决方案**：查看错误指出的行号，确保代码运行的时机正确，或者在它（例如 xhr.open
）之前添加了不必要的调用

延伸阅读：http://envato-support.dotonpaper.net/forums/topic/uncaught-urierror-uri-malformed-when-i-translate-word-available/

>个人见解：应该不是amWiki的错误，很有可能是url的格式不正确所致。如果默认文库可以正常工作的话，那么很有可能是自己引起的，我在自己输入html代码段的时候也遇到过类似的问题，希望对你有帮助啦><

**Comment by jimmywzm** [comment]
@YaoXuanZhi 

这个错误信息出现后，Atom提示我更新Atom，然后跟新后还是出现此error提示。
然后我尝试重启Atom，仍然不行，于是在网上找了各种方法也无法解决。

最后我尝试“通过confog.json创建新文库”，重新打开amWiki，error提示就消失了。
