### ISSUE TITLE
启动本地静态服务器出错Uncaught Error: listen EADDRINUSE :::5171

### ISSUE THREAD

**Issue by schneiderlin** [TevinLi/amWiki#46]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package 1.0.6

### Stack Trace

Uncaught Error: listen EADDRINUSE :::5171

```
At events.js:160

Error: listen EADDRINUSE :::5171
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at /packages/amWiki/build/server.class.js:41:12)
    at /packages/amWiki/build/localServer.js:34:36
    at next (<anonymous>)
    at onFulfilled (/packages/amWiki/modules/co.js:65:19)
```

### Commands

```
     -1:56 amWiki:runServer (input.hidden-input)
     -1:47.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:12.4.0 amWiki:runServer (input.hidden-input)
     -1:10.1.0 amWiki:browser (input.hidden-input)
     -1:04.9.0 amWiki:runServer (input.hidden-input)
     -1:02.0 amWiki:browser (input.hidden-input)
```

### Non-Core Packages

```
amWiki 1.0.6 
```

**Comment by TevinLi** [comment]
这是端口被占用了，应该是多开的问题，后面我会加入终端对多开的兼容处理，非常感谢你的反馈，thanks！

**Comment by TevinLi** [comment]
已于 [v1.1.2](https://github.com/TevinLi/amWiki/releases/tag/v1.1.2) 版本修复此问题
