### ISSUE TITLE
启动本地服务器报错误

### ISSUE THREAD

**Issue by yaojingtech** [TevinLi/amWiki#55]
[Enter steps to reproduce:]

1. 编辑文档
2. 在atom编辑器上，点击对不awiki菜单，然后点击 启动本地web静态服务器。

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**:  windows10 
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package 1.1.1

### Stack Trace

Uncaught Error: listen EADDRINUSE :::5171

```
At events.js:160

Error: listen EADDRINUSE :::5171
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at /packages/amWiki/build/server.class.js:41:12)
    at /packages/amWiki/build/localServer.js:34:36
    at next (<anonymous>)
    at onFulfilled (/packages/amWiki/modules/co.js:65:19)
```

### Commands

```
     -4:59.1.0 core:move-right (input.hidden-input)
  2x -4:58.7.0 core:backspace (input.hidden-input)
     -4:32 editor:newline (input.hidden-input)
 17x -4:17.4.0 core:backspace (input.hidden-input)
  5x -3:33.4.0 core:move-left (input.hidden-input)
     -3:28.9.0 core:backspace (input.hidden-input)
     -3:27.5.0 core:move-right (input.hidden-input)
     -3:27.2.0 core:move-left (input.hidden-input)
  5x -3:25 core:move-right (input.hidden-input)
     -3:21.5.0 core:backspace (input.hidden-input)
  4x -3:21.1.0 core:move-left (input.hidden-input)
     -3:18.5.0 core:move-down (input.hidden-input)
     -3:08.3.0 core:save (input.hidden-input)
  2x -1:18.1.0 core:paste (input.hidden-input)
     -0:34.9.0 amWiki:runServer (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:32.8.0 amWiki:browser (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
amWiki 1.1.1 
markdown-pdf 1.5.0 
markdown-writer 2.6.5 
my-package 0.0.0 
simplified-chinese-menu 5.3.1 
```

**Comment by TevinLi** [comment]
重复的 issue at [#46](https://github.com/TevinLi/amWiki/issues/46)   

---
PS：本 issue 已于 [commit-384790b](https://github.com/TevinLi/amWiki/commit/384790bca8c19b93ab5c564b2685c9fd747502f9) 修复，请耐心等待 v1.1.2 发布
