### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\amWiki\package.json'

### ISSUE THREAD

**Issue by Beants** [TevinLi/amWiki#84]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package 1.2.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\micor\.atom\packages\amWiki\package.json'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'C:\Users\micor\.atom\packages\amWiki\package.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at /packages/amWiki-1.2.1/lib/main.js:104:55)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.7/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.19.7/resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.7/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```

```
     -2:12 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
     -1:56.3.0 tree-view:add-file (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:48.8.0 amWiki:create (input.hidden-input)
     -1:17.8.0 core:save (input.hidden-input)
     -1:02.0 core:paste (input.hidden-input)
     -1:00.9.0 core:save (input.hidden-input)
     -0:56.1.0 amWiki:create (input.hidden-input)
```

### Non-Core Packages

```
amWiki 1.2.1 
simplified-chinese-menu 5.3.4 
```

**Comment by TevinLi** [comment]
把 C:/Users/micor/.atom/packages/ 路径下的文件夹 `amWiki-1.2.1` 改名为 `amWiki` 即可
