### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by Git2Frank** [TevinLi/amWiki#87]
[Enter steps to reproduce:]

1. library里使用Atom创建编辑md文件，保存，UTF-8
2. 在浏览器打开文档，Atom出现此提示

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Windows 10 pro. x64
**Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package 1.2.1

### Stack Trace

Uncaught URIError: URI malformed

```
At C:\Users\username\.atom\packages\amWiki\files\gbk.js:77

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /packages/amWiki/files/gbk.js:77:24
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (native)
    at Object.decode (/packages/amWiki/files/gbk.js:76:16)
    at Server._parse (/packages/amWiki/build/server.class.js:157:28)
    at Server._nodeServer.http.createServer (/packages/amWiki/build/server.class.js:50:18)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at parserOnIncoming (_http_server.js:562:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

### Commands

```
  2x -8:29.3.0 core:backspace (input.hidden-input)
  2x -8:28.2.0 core:save (input.hidden-input)
     -7:08.9.0 core:backspace (input.hidden-input)
  3x -6:44.3.0 core:paste (input.hidden-input)
     -6:20.6.0 amWiki:paste (input.hidden-input)
  2x -6:17.7.0 core:backspace (input.hidden-input)
     -6:06.2.0 amWiki:paste (input.hidden-input)
     -6:04.7.0 core:backspace (input.hidden-input)
     -5:47.5.0 amWiki:paste (input.hidden-input)
     -5:45.9.0 core:backspace (input.hidden-input)
     -5:35.7.0 amWiki:paste (input.hidden-input)
     -5:34.4.0 core:backspace (input.hidden-input)
  2x -5:31.3.0 core:undo (input.hidden-input)
     -5:26.1.0 amWiki:paste (input.hidden-input)
     -5:24.6.0 core:backspace (input.hidden-input)
     -5:22.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
amWiki 1.2.1 
simplified-chinese-menu 5.3.4 
```

**Comment by Mkv4** [comment]
> [Enter steps to reproduce:]
> 
> 1. library里使用Atom创建编辑md文件，保存，UTF-8
> 2. 在浏览器打开文档，Atom出现此提示
> 
> **Atom**: 1.21.0 x64
> **Electron**: 1.6.9
> **OS**: Windows 10 pro. x64
> **Thrown From**: [amWiki](https://github.com/TevinLi/amWiki) package 1.2.1
> 
> ### Stack Trace
> Uncaught URIError: URI malformed
> 
> ```
> At C:\Users\username\.atom\packages\amWiki\files\gbk.js:77
> 
> URIError: URI malformed
>     at decodeURIComponent (<anonymous>)
>     at /packages/amWiki/files/gbk.js:77:24
>     at RegExp.[Symbol.replace] (<anonymous>)
>     at String.replace (native)
>     at Object.decode (/packages/amWiki/files/gbk.js:76:16)
>     at Server._parse (/packages/amWiki/build/server.class.js:157:28)
>     at Server._nodeServer.http.createServer (/packages/amWiki/build/server.class.js:50:18)
>     at emitTwo (events.js:106:13)
>     at Server.emit (events.js:191:7)
>     at parserOnIncoming (_http_server.js:562:12)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
> ```
> ### Commands
> ```
>   2x -8:29.3.0 core:backspace (input.hidden-input)
>   2x -8:28.2.0 core:save (input.hidden-input)
>      -7:08.9.0 core:backspace (input.hidden-input)
>   3x -6:44.3.0 core:paste (input.hidden-input)
>      -6:20.6.0 amWiki:paste (input.hidden-input)
>   2x -6:17.7.0 core:backspace (input.hidden-input)
>      -6:06.2.0 amWiki:paste (input.hidden-input)
>      -6:04.7.0 core:backspace (input.hidden-input)
>      -5:47.5.0 amWiki:paste (input.hidden-input)
>      -5:45.9.0 core:backspace (input.hidden-input)
>      -5:35.7.0 amWiki:paste (input.hidden-input)
>      -5:34.4.0 core:backspace (input.hidden-input)
>   2x -5:31.3.0 core:undo (input.hidden-input)
>      -5:26.1.0 amWiki:paste (input.hidden-input)
>      -5:24.6.0 core:backspace (input.hidden-input)
>      -5:22.8.0 core:save (input.hidden-input)
> ```
> ### Non-Core Packages
> ```
> amWiki 1.2.1 
> simplified-chinese-menu 5.3.4 
> ```

虽然不知道具体原因是什么，但是如果一个文件夹下面是一个中文名的md文档就会报错，英文不会。如果一个文件夹下有一个子文件夹，子文件夹下的中文名的md文档不会报错。

**Comment by GrandMarch** [comment]
这个是你的文件名包含有#?等一些特殊字符导致的。今天我也到这个问题，但是我不知道怎么改。我对js一窍不通。我debug可一下，怀疑是build/server.class.js 中decodeURI的问题。我监视到，当文件名中有#时，#以后的内容被截取了，所以F12就打不开文档。但是再次点击文档时又可以打开，但是同时又报URI错误的异常。等着再仔细看看到底怎么回事
